[package]
name = "datastore-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polygon = { git = "ssh://git@github.com/Overmuse/polygon", tag = "v0.10.2", default-features = false, features = ["rest"] }
tokio = "1.7.1"
tokio-postgres = "0.7.2"
